#!/usr/bin/env python3
"""Build a C5 BFS wall-modeled LES smoke case from existing Branch D artifacts.

Inputs:
- v30_isothermal_rans_flibe_re10000_bfs: BFS mesh and converged RANS field.
- v26_les_smoke_flibe_re10000_bent_recirculation_wale: WALE/pimpleFoam smoke
  controls used for the existing outlet-offset LES lineage.

Output:
- c5_bfs_les_smoke_wale: runnable pimpleFoam case, isothermal velocity only.

This intentionally creates a smoke/preflight case, not a production LES.
"""

from __future__ import annotations

import argparse
import shutil
from pathlib import Path


ROOT = Path(__file__).resolve().parent
RANS_CASE = ROOT / "v30_isothermal_rans_flibe_re10000_bfs"
LES_TEMPLATE = ROOT / "v26_les_smoke_flibe_re10000_bent_recirculation_wale"
OUT_CASE = ROOT / "c5_bfs_les_smoke_wale"


CONTROL_DICT = """/*--------------------------------*- C++ -*----------------------------------*\\
| =========                 |                                                 |
| \\\\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox           |
|  \\\\    /   O peration     | Version:  2512                                  |
|   \\\\  /    A nd           | Website:  www.openfoam.com                      |
|    \\\\/     M anipulation  |                                                 |
\\*---------------------------------------------------------------------------*/
FoamFile
{
    version         2;
    format          ascii;
    class           dictionary;
    object          controlDict;
}

application     pimpleFoam;

startFrom       latestTime;

startTime       0;

stopAt          endTime;

endTime         0.8;

deltaT          0.0001;

writeControl    runTime;

writeInterval   0.05;

purgeWrite      0;

writeFormat     ascii;

writePrecision  6;

writeCompression off;

timeFormat      general;

timePrecision   6;

runTimeModifiable true;

adjustTimeStep  yes;

maxCo           0.5;

maxDeltaT       0.00025;

functions
{
    bfsProbes
    {
        type            probes;
        libs            ( "libsampling.so" );
        writeControl    timeStep;
        writeInterval   5;
        fields          ( U p );
        probeLocations
        (
            ( 0.111 -0.015 0.02 )
            ( 0.150 -0.015 0.02 )
            ( 0.220 -0.015 0.02 )
        );
    }

    inletP
    {
        type            surfaceFieldValue;
        libs            ( "libfieldFunctionObjects.so" );
        regionType      patch;
        name            inlet;
        operation       areaAverage;
        fields          ( p );
        writeControl    timeStep;
        writeInterval   5;
        writeFields     false;
    }

    outletP
    {
        type            surfaceFieldValue;
        libs            ( "libfieldFunctionObjects.so" );
        regionType      patch;
        name            outlet;
        operation       areaAverage;
        fields          ( p );
        writeControl    timeStep;
        writeInterval   5;
        writeFields     false;
    }
}


// ************************************************************************* //
"""


TURBULENCE_PROPERTIES = """/*--------------------------------*- C++ -*----------------------------------*/
FoamFile
{
    version     2.0;
    format      ascii;
    class       dictionary;
    object      turbulenceProperties;
}
// C5 BFS LES smoke case.  WALE SGS model, wall-modeled on the existing v30 BFS
// RANS mesh.  This is a paired diagnostic for v26/v27, not production LES.

simulationType  LES;

LES
{
    LESModel        WALE;
    turbulence      on;
    printCoeffs     on;
    delta           cubeRootVol;

    cubeRootVolCoeffs
    {
        deltaCoeff      1;
    }
}
"""


README = """# C5 BFS LES Smoke Case

Generated by `make_c5_bfs_les_smoke_case.py`.

Purpose: create the missing BFS leg for C5 geometry-LES comparison using the
same coarse wall-modeled WALE/pimpleFoam style as the existing v26 outlet-offset
LES smoke case.

Inputs:
- mesh and initial flow from `v30_isothermal_rans_flibe_re10000_bfs/1000`
- WALE/pimpleFoam controls from the v26 LES lineage, with BFS-specific probes

Recommended first commands:

```bash
checkMesh -case c5_bfs_les_smoke_wale
pimpleFoam -case c5_bfs_les_smoke_wale | tee c5_bfs_les_smoke_wale/log.pimpleFoam
pimpleFoam -case c5_bfs_les_smoke_wale -postProcess -func yPlus -latestTime
```

Report caveat: this is a smoke/preflight case, not wall-resolved, not
grid-converged, not statistically converged, and not validated.
"""


ALLRUN = """#!/usr/bin/env bash
set -euo pipefail

case_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

checkMesh -case "$case_dir" | tee "$case_dir/log.checkMesh"
pimpleFoam -case "$case_dir" | tee "$case_dir/log.pimpleFoam"
pimpleFoam -case "$case_dir" -postProcess -func yPlus -latestTime | tee "$case_dir/log.yPlus.latest"
"""


def copy_case(src: Path, dst: Path, force: bool) -> None:
    if dst.exists():
        if not force:
            raise SystemExit(f"{dst} already exists; pass --force to rebuild it")
        shutil.rmtree(dst)
    shutil.copytree(src, dst)


def remove_time_dirs(case: Path) -> None:
    for child in case.iterdir():
        if child.is_dir() and is_time_dir(child.name) and child.name != "0":
            shutil.rmtree(child)


def is_time_dir(name: str) -> bool:
    try:
        float(name)
    except ValueError:
        return False
    return True


def seed_zero_from_latest(case: Path, latest: str = "1000") -> None:
    zero = case / "0"
    latest_dir = case / latest
    if not latest_dir.exists():
        raise SystemExit(f"missing RANS seed directory: {latest_dir}")

    if zero.exists():
        shutil.rmtree(zero)
    zero.mkdir()

    for name in ("U", "p", "nut", "phi"):
        src = latest_dir / name
        if src.exists():
            shutil.copy2(src, zero / name)


def copy_les_numerics(case: Path, end_time: float) -> None:
    for name in ("fvSchemes", "fvSolution"):
        shutil.copy2(LES_TEMPLATE / "system" / name, case / "system" / name)
    control = CONTROL_DICT.replace("endTime         0.8;", f"endTime         {end_time:g};")
    (case / "system" / "controlDict").write_text(control)
    (case / "constant" / "turbulenceProperties").write_text(TURBULENCE_PROPERTIES)


def write_readme(case: Path) -> None:
    (case / "README.c5_bfs_les.md").write_text(README)


def write_allrun(case: Path) -> None:
    path = case / "Allrun.c5_bfs_les"
    path.write_text(ALLRUN)
    path.chmod(0o755)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--force", action="store_true", help="replace existing output case")
    parser.add_argument("--out", type=Path, default=OUT_CASE, help="output case directory")
    parser.add_argument("--end-time", type=float, default=0.8, help="pimpleFoam endTime")
    args = parser.parse_args()

    out = args.out if args.out.is_absolute() else ROOT / args.out
    copy_case(RANS_CASE, out, args.force)
    seed_zero_from_latest(out)
    remove_time_dirs(out)
    copy_les_numerics(out, args.end_time)
    write_readme(out)
    write_allrun(out)
    print(f"wrote {out}")
    print("next: checkMesh -case", out)


if __name__ == "__main__":
    main()
